### ISSUE TITLE
Auto forwarding cmd_result get_accepted bug

### ISSUE THREAD

**Issue by FletcherJ1** [eBay/NuRaft#131]
When using auto forwarding for appending entries, the accepted flag doesn't seem to get updated whereas when it doesn't use auto-forwarding (current node = leader) it updates the accepted flag. This leads to my code thinking there is an error because the accepted flag is false when everything is actually fine.

I think it just needs presult.accept() calling when checking if the original request is accepted to also update the result accept flag.

https://github.com/eBay/NuRaft/blob/17aab8d633b0187dc4a5d862aa75faf3ef91f5cd/src/handle_user_cmd.cxx#L180-L182

changed to:
```
if (resp->get_accepted()) {
     resp_ctx = resp->get_ctx();
     presult->accept();
}
```

It could also be my understanding of auto-forwarding being wrong and that is expected behaviour?

Thanks,
James.

**Comment by greensky00** [comment]
@FletcherJ1 
You're right, thanks for letting us know.

Would you mind submitting PR for this fix? Thanks.

**Comment by FletcherJ1** [comment]
Yeah of course. No worries.

**Comment by FletcherJ1** [comment]
I've made a patch for this but I'm not sure if it is the best way. I've added a method into cmd_result called wait which uses the internal condition variable wait. Then, when the callback is called from the rpc send method it calls set_result which notifies any waiting threads to continue. The wait/notify functionality is already present for set_result() and get() but I can't use get() due to the way append_entries() creates the cmd_result variable making get() immediately return because it thinks there is already a result.

Hope that makes sense. I can submit a separate PR for this or combine it into #132.

**Comment by greensky00** [comment]
Thanks @FletcherJ1 ! Let me merge your current PR first.

Regarding the sync forwarding thing, I think it will be better to use the existing `get()` function instead of adding `wait()`:
https://github.com/eBay/NuRaft/blob/17aab8d633b0187dc4a5d862aa75faf3ef91f5cd/include/libnuraft/async.hxx#L252-L269

If `set_result()` is somehow invoked earlier than `wait()`, the `wait()` function should check `has_result_` value to decide whether it will wait or not. And that logic is already implemented in `get()` function.

Please submit your new PR first. Then we can discuss it on the PR. Thanks.

**Comment by greensky00** [comment]
Thanks @FletcherJ1 ! I just merged your current PR.

Regarding `get()` and `wait()` function, can you please elaborate more? I believed `get()` will wait until `set_result()` is invoked, as `has_result_` is initialized to `false`. Once you submit your new PR first, and we can discuss it on the PR directly.

**Comment by FletcherJ1** [comment]
Okay, I'll submit a PR and discuss there. I'll close this since it's fixed.
