### ISSUE TITLE
Startup with fixed multinode configuration

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#179]
Hi!

As far as I understood from examples and issues NuRaft cluster startup should look like this:
1. Start `raft_server` on all nodes.
2. Choose one node (`S_l`) to add other nodes according to whatever rules.
3. If we are `S_l` call `add_srv` for all other nodes.
4. If we are not `S_l` just wait until we will be added to the cluster by `S_l`.

But this algorithm has several complexities on the user-side. For example, what we should do if `S_l` crashed after it was chosen to add other nodes? Probably we should use some timeouts, and try to choose another node to be `S_l'`. Or what we should do if one of the follower nodes doesn't respond to `add_srv`. Probably start without it, but try to add it in the background.

It would be much simpler if there would be a way to start all nodes with some fixed configuration and all leader/follower communication will be on the RAFT's side. This approach is described in the original paper:

> 
_When servers start up, they begin as followers. A server remains in follower state as long as it receives valid RPCs from a leader or candidate. Leaders send periodic heartbeats (AppendEntries RPCs that carry no log entries) to all followers in order to maintain their authority. If a follower receives no communication over a period of time called the election timeout, then it assumes there is no viable leader and begins an election to choose a new leader._

Are there any fundamental reasons why it's not implemented?

**Comment by greensky00** [comment]
Hi @alesapin 

It is not clear what you meant by "startup". Does that mean 1) initializing a Raft cluster (happening once at the beginning)? or 2) rebooting the already initialized Raft cluster?

The approach you refer to is already there. Every time a NuRaft instance is initiated, it calls `state_mgr::load_config()` to load the previous cluster config.
https://github.com/eBay/NuRaft/blob/f8fff26db0b3d5b91a8c49f91d994298bce5dc6c/include/libnuraft/state_mgr.hxx#L46

Whenever you add/remove servers, the new cluster config is written through `state_mgr::save_config()`.
https://github.com/eBay/NuRaft/blob/f8fff26db0b3d5b91a8c49f91d994298bce5dc6c/include/libnuraft/state_mgr.hxx#L53

It is up to you how to store the given cluster config. In the example we provide, we don't make them durable so that the Raft cluster should be re-initialized after rebooting. We mentioned that in here
https://github.com/eBay/NuRaft/blob/f8fff26db0b3d5b91a8c49f91d994298bce5dc6c/examples/in_memory_state_mgr.hxx#L50-L51

If you meant 1), you can let `load_config()` return the fixed configuration that you want at the beginning.

If 2), it should automatically work as long as your previous cluster config is durable on disk through `state_mgr::save_config()`.

**Comment by alesapin** [comment]
Thanks!
