### ISSUE TITLE
API for tracking cluster membership

### ISSUE THREAD

**Issue by kishorekrd** [eBay/NuRaft#199]
I see that list command lists the configured servers in the cluster, but they are not necessarily up at that time.
How to list the servers that are only up?

Is there any API to get the details of down followers and track cluster membership?
How can I add a call-back function to be called when any follower goes down or comes up?

**Comment by kishorekrd** [comment]
Hi @greensky00 , 
Thanks for your responses. Any suggestions on the API for cluster membership tracking?
Thanks

**Comment by greensky00** [comment]
Hi @kishorekrd 

"membership" itself never changes according to online/offline status, unless users explicitly do add/remove server to/from the cluster.

The term "offline" is ambiguous and cannot be defined clearly due to millions of situations as follows:
* The follower is still "online", but the leader just cannot see it due to network partition.
* The follower is still "online", but just slow so that cannot respond to a few heartbeats.
* The follower is still "online", and still responds to heartbeats, but its log index is lagging behind the majority of members. And the log gap is getting bigger.
* The leader is isolated so that it thinks all the others are "offline", but actually the other members are alive; they form a quorum and elect a new leader, but the old leader does not know about that. From the other members' point of view, the old leader is "offline".

Hence, keeping tracking of "offline" status cannot give us meaningful information for the Raft protocol itself. If you want to track "offline" status, you need to define "what offline is", and implement it outside Raft.

Please note that we provide a few callbacks for the "freshness" of followers:
https://github.com/eBay/NuRaft/blob/8699f3b81d33b239dddc37a18fa205c6a7b49c6a/include/libnuraft/callback.hxx#L99-L113

**Comment by greensky00** [comment]
+) 
One thing NuRaft can do additionally is providing an API that reports "the last time each follower responded", like the below:
```
follower1: responded 10 ms ago
follower2: responded 900 ms ago
follower3: responded 5,120 ms ago
```
From that information, you can decide the up/down status of each follower based on your criteria.

**Comment by kishorekrd** [comment]
Thanks for the response. What is the callback function for the leader to call if any follower is not responding or some follower, which went down before came back ?

**Comment by greensky00** [comment]
> connect to any node and find the leader details, then send request to the leader.
Yes. But usually, a leader does not change frequently so that you can remember the last leader and directly reach out to the leader next time. Then the 2-step method will happen only when the leader changes.

What about the API that I mentioned here? Do you think it will be helpful for you?
https://github.com/eBay/NuRaft/issues/199#issuecomment-826352910

**Comment by kishorekrd** [comment]
Yes, API that you mentioned at #199 (comment) is helpful. Is this API already available or planing to add?

**Comment by greensky00** [comment]
Ok. It is a brand new API and will be added soon.

**Comment by kishorekrd** [comment]
Thanks,
