### ISSUE TITLE
In the raft protocol, what happens if some nodes fail to execute the commit function？

### ISSUE THREAD

**Issue by guoxiangzhou** [eBay/NuRaft#254]
Can I use the return value of pre_commit to control whether the first phase of log replication succeeds or fails？

**Comment by greensky00** [comment]
Hi @guoxiangzhou 
`pre_commit` happens right after the log-append and before the replication, hence the return value of `pre_commit` does not reflect the log replication. 

And your question regarding commit is somewhat not clear to me. Are you referring to 1) Raft log commit (reaching consensus by quorum) or 2) `commit` of state machine?

If 1), the leader will keep trying to reach the consensus (or leader election may happen). If 2), the execution result of the state machine is out of scope from Raft's perspective. Raft will move forward, and the state machine is purely your logic so that how to handle the execution result is up to you.

**Comment by guoxiangzhou** [comment]
Thx. Therefore, raft is only responsible for the full synchronization of logs, regardless of the execution results of logs.

**Comment by greensky00** [comment]
That's correct.
