### ISSUE TITLE
How much performance decreasing of 3 node comparing to 1 node of nuraft?

### ISSUE THREAD

**Issue by zhanglistar** [eBay/NuRaft#274]
Background is:
We have implemented an alternative zookeeper with nuraft in clickhouse, named clickhouse-keeper.

I have tested in my cluster happening to see a strange thing: 
In 1 node cluster, clickhouse-keeper performance is about 1.4x of zookeeper in only writing benchmark, about 6.3MBps.
But in 3 nodes cluster, just 50%-70% throughput of zookeeper, about 1.5Mbps, throughput decreasing about 4.2x.
Details on pr: https://github.com/ClickHouse/ClickHouse/pull/33180
I also notice that disk IO is about 100%, the bottleneck is this. Maybe our batch is about 50 log entry not as large as zookeeper with 1000 log entry.

Question: is that ok to see a 4.2x performance decreasing from 1 node to 3 nodes cluster?

Thanks a lot for your advices.

**Comment by greensky00** [comment]
Hi @zhanglistar 

The main difference between 1 node vs. 3 nodes is that:
```
1 node:
1) S1: append log
2) S1: commit the log into the state machine
```
```
3 nodes:
1) S1: append log
2) S1: send the log to S2 (and S3)
3) S2: append log
4) S2: return the response back to S1
5) S1: commit the log into the state machine
```
you have additional steps 2), 3), and 4) (note that the other server S3 won't have any impact as quorum size is 2), thus it depends on either network (2 and 4) or disk (3) whichever slower one dominates.

But generally, it shouldn't be 4.2x. Did you run 3 servers on the same machine?

**Comment by zhanglistar** [comment]
> 

The 3 nodes are on the same physical datacenter, but not on the same machine.
In Nuraft, are 1) append log and 2) send log to s2(s3) parallel? I have seen this optimization in raft in tidb raft.

**Comment by greensky00** [comment]
1. 1) appending log in s1 should succeed before 2) replication, otherwise it will break the protocol. Replication to s2 and s3 can be parallel.
2. Next `AppendEntries` (including heartbeat) message will contain additional info regarding the latest committed log index. This is described in the original Raft paper.
3. No, the leader returns the response as soon as s1's state machine commits the log.

**Comment by zhanglistar** [comment]
> 3\. No, the leader returns the response as soon as s1's state machine commits the log.

`No, the leader returns the response as soon as s1's state machine commits the log.`  This will break the protocol? 
Say: if leader(say s1) commit the log and response success to client.
2 followers(say s2 s3) not commit log, only append log to log store. 
Then leader fails because of power failure or something else. 
If s2 becomes leader, client read from s2, and get stale message.

**Comment by greensky00** [comment]
If the current app is using a single thread, calling `append_entries` in sync mode, and waiting for the response before calling the next request, then that is bad for throughput for sure. If that's the case, using the async mode will help.

Another one is increasing `max_append_size_`, you may need to find the optimal batch size.

If the log store calls `fsync` for each `append` or `write_at` API, that is also not good. `fsync` should be moved to `end_of_append_batch` API so as to do disk write once for each batch.

**Comment by zhanglistar** [comment]
> If the current app is using a single thread, calling `append_entries` in sync mode, and waiting for the response before calling the next request, then that is bad for throughput for sure. If that's the case, using the async mode will help.
> 
> Another one is increasing `max_append_size_`, you may need to find the optimal batch size.
> 
> If the log store calls `fsync` for each `append` or `write_at` API, that is also not good. `fsync` should be moved to `end_of_append_batch` API so as to do disk write once for each batch.

Thanks a lot. I will try.

**Comment by zhanglistar** [comment]
> 

`No, the leader returns the response as soon as s1's state machine commits the log.`
About this, I have a question: 
Say s1 is now leader, s2 and s3 is follower.
1. s1 receive client log, and append to log store locally and replicate the log to s2 and s3, but only s2 success, and s3 not responding.
2. s1 sees that majority append log, commit log to state machine 
3. reply to client success.
4. but s1 down because of power failure maybe in step 2 or 3
5. s2 becomes leader, s2 should commit or not commit the log?
If it commits the log, then if s1 down before 3, inconsistent.
If it does not commit the log, then if s1 down after 3, inconsistent.

**Comment by zhanglistar** [comment]
> 

`(1) appending log in s1 should succeed before (2) replication, otherwise it will break the protocol. Replication to s2 and s3 can be parallel.` This optimization also seen in braft and tidb raft, it seems that not breaking the protocol, the log is already replicated to majority nodes, leader can commit the log to state machine. Which one does it break the protocol?
Thanks in advance.

**Comment by greensky00** [comment]
@zhanglistar 
Let's say we have S1, S2, and S3, and S1 is the leader. Assume that the current term is 1, and the last log index is 10.

* S1 appends a new log (index number 11, term 1).
* S1 replicates log 11 to S2 and S3. And S1 requests writing log 11 to its local log store in parallel.
* Replication to S2 succeeds and S3 failed.
* S1 commits log 11 and returns "success" response to the client (still log 11 is not written to disk).
* S1 dies and then restarts. log 11 is lost.
* S1 initiates a leader election, and {S1, S3} forms a quorum, as both S1 and S3 have log index 10 as the last log. S1 becomes a leader for term 2.
* S2 will rollback log 11 due to term mismatch. 
* Data loss happens.

There are many more cases derived from the above situation.

Note that even in the current NuRaft, you can implement a similar optimization. You can call `fsync` asynchronously in another thread and make `append` or `write_at` or `end_of_append_batch` non-blocking. Then you can achieve the same result.

**Comment by zhanglistar** [comment]
> @zhanglistar Let's say we have S1, S2, and S3, and S1 is the leader. Assume that the current term is 1, and the last log index is 10.
> 
> * S1 appends a new log (index number 11, term 1).
> * S1 replicates log 11 to S2 and S3. And S1 requests writing log 11 to its local log store in parallel.
> * Replication to S2 succeeds and S3 failed.
> * S1 commits log 11 and returns "success" response to the client (still log 11 is not written to disk).
> * S1 dies and then restarts. log 11 is lost.
> * S1 initiates a leader election, and {S1, S3} forms a quorum, as both S1 and S3 have log index 10 as the last log. S1 becomes a leader for term 2.
> * S2 will rollback log 11 due to term mismatch.
> * Data loss happens.
> 
> There are many more cases derived from the above situation.
> 
> Note that even in the current NuRaft, you can implement a similar optimization. You can call `fsync` asynchronously in another thread and make `append` or `write_at` or `end_of_append_batch` non-blocking. Then you can achieve the same result.

The problem is in 3rd step, even s1 appends log to local log store and replicates the log s2/s3 parallel, s1 still commits the log to state machine after it receives the majority success response. In 3rd step, if s3 failed and s2 success, but local log store commit not success, s1 should not commit the log.

**Comment by greensky00** [comment]
> leader can commit the log to state machine even not to leader local log store.

@zhanglistar This is what you mentioned, so I put the above example.

Even if S1 waits for the local log store commit, that is also problematic:

* S1 appends a new log (index number 11, term 1).
* S1 replicates log 11 to S2 and S3. And S1 requests writing log 11 to its local log store in parallel.
* Replication to S2 succeeds and S3 failed.
* Writing to S1's local log fails, the operation for log 11 is canceled.
* New write request comes in, S1 appends the data with log index number 11.
* At this time, the replication to S3 succeeds, replication to S2 failed, writing to S1's log store succeeds.
* Now, split-brain happens: log 11 in S2 and S1/S3 are different.

**Comment by zhanglistar** [comment]
> 

I mean leader should wait majority append log success, the local log store or s1 or s2. If s1 and s2 response success, then leader can commit the log even if local store not response.

**Comment by greensky00** [comment]
@zhanglistar I understand what you said, but the actual problem is the situation when "leader's log store fails to append, while the other server (but not majority) has the failed log in its log store". Of course, the commit of the log should fail, but what happens to the log that the other server has? Since Raft does not allow a hole in the log index number, the leader should use the same log index number, and that will result in a split-brain. This should be handled separately, but this is not Raft, hence not proven about its safety.

**Comment by greensky00** [comment]
The solution that I can think of now without breaking the protocol is, when the leader's log store fails to append a log, killing the leader immediately, in order to avoid using the same term for the same index number. So that the stale log that the other server has should be rolled back by other log with the same index number but different term, and this is done by Raft naturally.

**Comment by zhanglistar** [comment]
> 

` "leader's log store fails to append, while the other server (but not majority) has the failed log in its log store".` What do you mean the failed log? The log appending is atomic, either log in the log store or no. There is no failed log?

**Comment by zhanglistar** [comment]
> The solution that I can think of now without breaking the protocol is, when the leader's log store fails to append a log, killing the leader immediately, in order to avoid using the same term for the same index number. So that the stale log that the other server has should be rolled back by other log with the same index number but different term, and this is done by Raft naturally.

Slow disk actually is a common thing, not a IO error.

**Comment by greensky00** [comment]
Let's say we are replicating log 11 with term 1. There are 3 parallel tasks for the leader:
1. Sending log 11 to S2.
2. Sending log 11 to S3.
3. Writing log 11 to its (S1) local log store.

Task (3) can fail anytime, due to various reasons, lack of disk space is the most common cause.

Suppose that task 1 succeeds, tasks 2, 3 fail. Then log 11 is not committed, but S2 still has log 11 with term 1. But log 11 does not exist in S1 and S3.

Now let's assume that the disk problem disappears by reclaiming more space, and a new write request comes into S1. S1 appends the data to the log store. Since the log store's current last log index is 10, it will assign log index 11 to the new data. Now log 11 in S1 and S2 are different. It is a split-brain that never happens if we append the log in the leader before the replication.

So, the solution is, as soon as the task (3) fails, step down S1 (leader). Then all 3 servers can be the next leader:
* S1 becomes the leader for term 2 again, by the vote from S1 and S3.
* S2 becomes the leader for term 2, by the vote from S2 and S1/S3.
* S3 becomes the leader for term 2, by the vote from S1 and S3.

If S2 becomes the leader, it will soon commit log 11 and everyone is happy. However, if S1 or S3 becomes the leader, the log 11 that S2 has should be discarded. But in this case, it is not a split-brain anymore, because the term is increased. It is naturally done by Raft, by replicating log 11 with term 2. Since S2's log 11 is term 1, it will be overwritten by log 11 with term 2.

**Comment by zhanglistar** [comment]
Thanks for your explain. That's indeed not easy to deal with, but It does improve the slow disk performance.
https://github.com/baidu/braft this can be refered.

**Comment by greensky00** [comment]
Since log 11 couldn't be replicated to the majority (only S2 has), it is ok that S1 or S3 be a leader. And also they should be able to be a leader because right after S1's step down, S2 may not be available (server offline or network partition).

But as long as S1 or S3 can resolve the conflict of the previous log 11, that is completely fine.

Let me think about how to deal with parallel log-append based on the current log store API. Thanks for your suggestion!

**Comment by zhanglistar** [comment]
> 

Thanks for your great explain. Expecting the feature!
