### ISSUE TITLE
What does cmd_result could assure if I set when_ready?

### ISSUE THREAD

**Issue by zhanglistar** [eBay/NuRaft#279]
Say, I write the code that `auto cmd_result = server.append_entries(); cmd_result.when_ready(this, my_callback_function);`
Then, in what condition that `my_callback_function` will not be called? or what does cmd_result class assure?
Thanks in advance.

**Comment by greensky00** [comment]
The callback function is always invoked whether the operation succeeds or fails.

If replication fails, the leader keeps retrying the replication until it loses its leadership after [the given period of time](https://github.com/eBay/NuRaft/blob/master/docs/leadership_expiration.md) or it receives a heartbeat from the new leader. Once its role becomes a non-leader, all pending operations are cancelled, and at that time the callback function is invoked.

Otherwise, if the leadership expiration is set to a negative number so that the leader never resigns, and also the old leader is isolated and does not receive heartbeats from the new leader, the callback is invoked when the server shuts down.

**Comment by zhanglistar** [comment]
Thanks.
