### ISSUE TITLE
Avoid simultaneously snapshot.

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#371]
### Issue
Avoid simultaneously snapshot to avoid all nodes being not available in a moment for  long time snapshoting.

NuRaft provides `chk_create_snapshot` method with which user can determine when to snapshot. But maybe it is more user friendly to make it default.  

So @greensky00 what is your opinion?

### Solution

Add `cur_snapshot_distance_` to `raft_server` and set it to `params->snapshot_distance_ /2 + random(params->snapshot_distance_ / 2)`

**Comment by greensky00** [comment]
Snapshot distance can be a critical configuration for performance tuning, so randomly changing the distance will not be preferred.

Instead of using a randomized value for each snapshot creation, we can use the randomized snapshot distance only once for the first snapshot. After that, even though the fixed snapshot distance is used, all members will create snapshots at different times.

For example, there are three servers: S1, S2, and S3, and the snapshot distance is 1000. We calculate the initial randomized snapshot distance as `snapshot_distance_ / 2 + random(snapshot_distance_ / 2)`. Let's assume S1, S2, and S3's initial distances are 600, 750, and 850, respectively. After that, even though we use the fixed distance 1000, S1 will create snapshots at 600, 1600, 2600, while S2 and S3 will do it at 750, 1750, 2750, and 850, 1850, 2850, so we can successfully avoid simultaneous snapshot creation with deterministic distance.

And this should be optional; by adding `enable_randomized_snapshot_creation_` in `raft_params,` the default should be `false`.
